name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint & Type Check

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra test

    - name: Run ruff (linter)
      run: |
        uvx ruff check .

    - name: Run ruff (formatter check)
      run: |
        uvx ruff format --check .

    - name: Run mypy (type checking)
      run: |
        uvx mypy langchain_naver_community

  test:
    runs-on: ubuntu-latest
    name: Tests

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra test

    - name: Run tests with pytest
      run: |
        pytest --cov=langchain_naver_community --cov-report=xml --cov-report=term-missing tests/
      env:
        NAVER_CLIENT_ID: test_client_id
        NAVER_CLIENT_SECRET: test_client_secret

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: false